export const RECEIVE_SNAPSHOTS = 'RECEIVE_SNAPSHOTS';
export const RECEIVE_SNAPSHOT = 'RECEIVE_SNAPSHOT';
export const SET_SELECTED_SNAPSHOT = 'SET_SELECTED_SNAPSHOT';

export const RECEIVE_LIVECODE = 'RECEIVE_LIVECODE';
export const SET_PATH = 'SET_PATH';

